import os
import subprocess
import sys

Import('env')

def run_command(cmd, *args, **kwargs):
    returncode = subprocess.call(cmd, **kwargs)
    if returncode != 0:
        sys.exit(returncode)

def build_python(target, source, env):
    # Configure 
    run_command('./configure LDFLAGS="-static -static-libgcc" CPPFLAGS="-static"', cwd=env['PYTHON_PATH'], shell=True)

    # Make
    run_command('make {target}'.format(target=os.path.basename(env['PYTHON_LIB'])), cwd=env['PYTHON_PATH'], shell=True)

python_lib = env.Command(target=env['PYTHON_LIB'],
    source=Glob(os.path.join(env['PYTHON_PATH'], '*.c')),
    action=Action(build_python, 'Building \033[33m%s\033[0m...' % env['PYTHON_LIB']))
