import os

Import('env')

SOURCE_EXTS = ['*.c', '*.cpp']

def setup_plugins_dir(target, source, env):
    plugins_dir = target[0].abspath
    if not os.path.exists(plugins_dir):
        os.makedirs(plugins_dir)

sources = []
for dirpath, dirnames, filenames in os.walk(env['SRC_DIR']):
    for ext in SOURCE_EXTS:
        sources.append(Glob(os.path.join(dirpath, ext)))

program = env.Program(env['PROGRAM'], sources)
env.Depends(program, env['PYTHON_LIB'])

plugins_dir = env.Command(target=os.path.join(env['BUILD_DIR'], 'plugins'), source=sources,
    action=Action(setup_plugins_dir, 'Setting up plugins directory...'))
env.Depends(plugins_dir, program)

